config/routes.rb
Rails.application.routes.draw do
  root to: "podcasts#index"

  #search routes
  get "/search", to: "searches#apple", as: "search"
  post "/search", to: "searches#results"

  # session routes
  get "/login_form", to: "sessions#login_form", as: "login_form"
  post "/login", to: "sessions#login", as: "login"
  delete "/logout", to: "sessions#logout", as: "logout"
  get "/profile", to: "users#profile", as: "profile"
  get "/profile/followships", to: "users#followshipslist", as: "followshipslist"

  # podcasts routes
  resources :podcasts, only: [:show, :index]
  post "/podcasts/:id/subscription", to: "podcasts#subscription", as: "subscription"
  get "/podcasts_query", to: "podcasts#query"

  #episode routes
  resources :episodes, only: [:show]
  post "/episodes/:id/favouritisation", to: "episodes#favouritisation", as: "favouritisation"
  post "/episodes/:id/play", to: "episodes#play", as: "play"

  # user routes
  resources :users
  post "/users/:id/followship", to: "users#followship", as: "followship"

  #keyword routes
  resources :keywords, only: [:show]

  # note routes
  resources :notes

end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes, dependent: :destroy
  has_many :annotated_episodes, through: :notes, dependent: :destroy
  has_many :favouritisations, dependent: :destroy
  has_many :favourite_episodes, through: :favouritisations, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :podcasts, through: :subscriptions, dependent: :destroy

  validates :username, uniqueness: true, presence: true
  # validates :password_digest, presence: true

  has_secure_password

  has_many :active_relationships, class_name:  "Followship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed, dependent: :destroy
  has_many :passive_relationships, class_name:  "Followship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower, dependent: :destroy

  def toggle_subscription(podcast)
    !self.podcasts.include?(podcast) ? self.podcasts.push(podcast) : self.podcasts.delete(podcast)
  end

  def toggle_favouritisation(episode)
    !self.favourite_episodes.include?(episode) ? self.favourite_episodes.push(episode) : self.favourite_episodes.delete(episode)
  end

  def toggle_followship(followed)
    !self.following.include?(followed) ? self.following.push(followed) : self.following.delete(followed)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    session[:user_id] ? @me = User.find(session[:user_id]) : @me = nil
    @podcasts = @user.podcasts
    @favourite_episodes = @user.favourite_episodes
    @notes = @user.notes
  end

  def new
    if current_user
      redirect_to current_user
    else
      @user = User.new
    end
  end

  

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      @podcasts = @user.podcasts
      @favourite_episodes = @user.favourite_episodes
      @notes = @user.notes
      redirect_to @user
    else
      flash[:notice] = "User creation failed. Please try again"
      redirect_to new_user_path
    end
  end

  def profile
    if !@current_user
      flash[:notice] = "Please sign in to continue!"
      redirect_to login_form_path
    else
      @user = User.find(session[:user_id])
      @podcasts = @user.podcasts
      @favourite_episodes = @user.favourite_episodes
      @notes = @user.notes
      @id = session[:user_id]
    end
  end

  def edit

  end

  def update

  end

  def destroy
    User.find(session[:user_id]).destroy
    session[:user_id] = nil
    redirect_to "/"
  end

  def followship
    @user = User.find(params[:id])
    session[:user_id] ? @me = User.find(session[:user_id]) : @me = nil
    current_user.toggle_followship(@user)
    redirect_to @user
  end

  def followshipslist
    if !@current_user
      flash[:notice] = "Please sign in to continue!"
      redirect_to login_form_path
    elsif @current_user && (params[:q]=="following")
      @user = User.find(session[:user_id])
      @following = @user.following
      @followers = @user.followers
      @followships = @following
    elsif @current_user && (params[:q]=="followers")
      @user = User.find(session[:user_id])
      @following = @user.following
      @followers = @user.followers
      @followships = @followers
    else
      @user = User.find(session[:user_id])
      @following = @user.following
      @followers = @user.followers
      @followships = (@following + @followers).uniq
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followshipslist.html.erb
<section class="w-75 mx-auto">
<div class="text-center display-4">Your Followships</div>

<p>&nbsp;</p>
<p class="text-center"><%= link_to "all followships", "/profile/followships"%> | <%= link_to "followers only", "/profile/followships?q=followers"%> | <%= link_to "following only", "/profile/followships?q=following"%></p>

<ul class="list-group list-group-flush">
  <% @followships.each do |f|%>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <%= link_to f.username, f %>(<% if @followers.include?(f) && @following.include?(f)%>you follow each other<%elsif @followers.include?(f) && !@following.include?(f)%>following you<%elsif !@followers.include?(f) && @following.include?(f)%>you follow<%end%>)
    </li>
  <% end %>
</ul>

</section>

app/views/users/new.html.erb
<div class="text-center">

  <h3>User creation</h3>

  <%= form_for @user, class: "form-group" do |f| %>
    <%= f.text_field :username, class: "form-control col-xs-4", placeholder: "username" %><br>
    <%= f.password_field :password, class: "form-control", placeholder: "password" %><br>
    <%= f.submit %>
  <% end%>

</div>

app/views/users/profile.html.erb
<section class="w-75 mx-auto">
<div class="text-center display-4">Welcome back, <%= @user.username%>!
</div>

<p align="center"><a href="#account">Account Management</a> | <a href="#podcasts">Subscribed Podcasts</a> | <a href="#favourite_episodes">Favourite Episodes</a> | <a href="#annotations">Annotations</a></p>
<p>&nbsp;</p>

<a name="account"></a>
<h4>Account Management</h4>
<%= button_to "Delete Account", {action: "destroy", id: @id, style: {display: :inline}}, {method: "delete", data: {confirm: "Are you sure?"}}%>

<br>
<h4><%= link_to "Your Followships", "/profile/followships"%></h4>
<br>
<a name="podcasts"></a>

<h4>Subscribed podcasts</h4>
<% @podcasts.each_slice(3) do |group| %>
<div class="row">
  <% group.each do |p| %>
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= link_to p.name, p %></h5>

        <div class="card-text text-center">
          <img src=<%=p.url%> width="150" height="150"><br><%= (p.description.length>100) ? p.description.first(80) + "..." : p.description %>
        </div>

        <div class="card-footer">
          <small class="text-muted">Categories: <% p.categories.each do |c| %><%= link_to c.name, "/podcasts?category=#{c.id}" %> | <% end %></small>
        </div>

    </div>
   </div>
   </div>
   <% end %>
<p>&nbsp;</p>
</div>
<% end %>

<a name="favourite_episodes"><h4>Favourite episodes</h4></a>
<% @favourite_episodes.each_slice(3) do |group| %>
<div class="row">
  <% group.each do |fe| %>
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= link_to fe.title, fe%></h5>
        <p class="card-text"><%= fe.description%></p>
      </div>
      <div class="card-footer">
        <small class="text-muted">from <%=link_to fe.podcast.name, fe.podcast %></small>
      </div>
    </div>
   </div>
   <% end %>
<p>&nbsp;</p>
</div>
<% end %>

<p>&nbsp;</p>

<a name="annotations"><h4>Annotations</h4></a>
<%@notes.each_slice(3) do |group|%>
<div class="row">
  <% group.each do |n|%>
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <p class="card-text"><%= n.content%></p>
      </div>
      <div class="card-footer">
        <small class="text-muted">on: <%=link_to n.annotated_episode.title, n.annotated_episode%> from <%=link_to n.annotated_episode.podcast.name,n.annotated_episode.podcast%></small>
      </div>
    </div>
   </div>
   <% end %>
<p>&nbsp;</p>
</div>
<% end %>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</section>

app/views/users/show.html.erb
<header>
  <div class="text-center display-4"><%= @user.username%></div>
  <p>&nbsp;</p>
  <div class="text-center">
      <%= (button_to((@me.following.include?(@user) ? "unfollow" : "follow"), followship_path)) if @me %>
  </div>
</header>
<p>&nbsp;</p>
<section class="w-75 mx-auto">

<!-- <p align="center">Skip to content: <a href="#podcasts">Subscribed Podcasts</a> | <a href="#favourite_episodes">Favourite Episodes</a> | <a href="#annotations">Annotations</a></p> -->
<a name="podcasts"></a>

<h4>Subscribed podcasts</h4>
<% @podcasts.each_slice(3) do |group| %>
<div class="row">
  <% group.each do |p| %>
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= link_to p.name, p %></h5>
        <p class="card-text"><%= (p.description.length>100) ? p.description.first(80) + "..." : p.description %></p>
      </div>
      <div class="card-footer">
        <small class="text-muted"><% p.categories.each do |c| %><%= link_to c.name, "/podcasts?category=#{c.id}" %> | <% end %></small>
      </div>
    </div>
   </div>
   <%end%>
<p>&nbsp;</p>
</div>
<%end%>

<p>&nbsp;</p>
<a name="favourite_episodes"></a>
<h4>Favourite episodes</h4>
<% @favourite_episodes.each_slice(3) do |group| %>
<div class="row">
  <% group.each do |fe| %>
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= link_to fe.title, fe %></h5>
        <p class="card-text"><%= fe.description %></p>
      </div>
      <div class="card-footer">
        <small class="text-muted">from <%= link_to fe.podcast.name, fe.podcast %></small>
      </div>
    </div>
   </div>
   <% end %>
<p>&nbsp;</p>
</div>
<% end %>

<p>&nbsp;</p>

<a name="annotations"></a>
<h4>Annotations</h4>
<% @notes.each_slice(3) do |group| %>
<div class="row">
  <% group.each do |n| %>
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <p class="card-text"><%= n.content %></p>
      </div>
      <div class="card-footer">
        <small class="text-muted">on: <%= link_to n.annotated_episode.title, n.annotated_episode %> from <%= link_to n.annotated_episode.podcast.name,n.annotated_episode.podcast %></small>
      </div>
    </div>
   </div>
   <%end%>
<p>&nbsp;</p>
</div>
<%end%>
<p>&nbsp;</p>

<h4>Followers: (<%= @user.followers.count %>)</h4>
<% @user.followers.each do |f| %><li><%= link_to f.username, f %></li><% end %>

<h4>Following: (<%=@user.following.count%>)</h4>
<% @user.following.each do |f| %><li><%= link_to f.username, f %></li><% end %></h4>
</section>