config/routes.rb
Rails.application.routes.draw do
  root to: "podcasts#index"

  #search routes
  get "/search", to: "searches#apple", as: "search"
  post "/search", to: "searches#results"

  # session routes
  get "/login_form", to: "sessions#login_form", as: "login_form"
  post "/login", to: "sessions#login", as: "login"
  delete "/logout", to: "sessions#logout", as: "logout"
  get "/profile", to: "users#profile", as: "profile"
  get "/profile/followships", to: "users#followshipslist", as: "followshipslist"

  # podcasts routes
  resources :podcasts, only: [:show, :index]
  post "/podcasts/:id/subscription", to: "podcasts#subscription", as: "subscription"
  get "/podcasts_query", to: "podcasts#query"

  #episode routes
  resources :episodes, only: [:show]
  post "/episodes/:id/favouritisation", to: "episodes#favouritisation", as: "favouritisation"
  post "/episodes/:id/play", to: "episodes#play", as: "play"

  # user routes
  resources :users
  post "/users/:id/followship", to: "users#followship", as: "followship"

  #keyword routes
  resources :keywords, only: [:show]

  # note routes
  resources :notes

end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :podcast
  has_many :keywordisations
  has_many :keywords, through: :keywordisations
  
  has_many :notes, dependent: :destroy
  has_many :notators, through: :notes, dependent: :destroy
  has_many :favouritisations, dependent: :destroy
  has_many :favouriters, through: :favouritisations, dependent: :destroy

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def show
    @episode = Episode.find(params[:id])
    @podcast = @episode.podcast
    @favouriters = @episode.favouriters
    @notes = @episode.notes
    @keywords = @episode.keywords
    @user = current_user
    if @podcast.episodes.size > 1
      @siblings = @podcast.episodes.select{|e| e != @episode}
    end
    @note = Note.new
  end

  def favouritisation
    episode = Episode.find(params[:id])
    current_user.toggle_favouritisation(episode)
    redirect_to podcast_path(episode.podcast)
  end

  def play

  end

end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/index.html.erb
<div>
    <p class="text-center display-2">episodes</p>
    <p class="text-center display-5"><%= @keyword %></p>
</div>

<section class="w-75 mx-auto">
  <%=form_tag episodes_path, method: :get do%>
  <%=select_tag "keyword", options_from_collection_for_select(@keywords, :id, :keyword_episodes_count), class:"custom-select custom-select-lg mb-3", onchange: "this.form.submit();", include_blank: "-- Filter by Keyword (number of episodes in this category)"%>
  <%end%>

<p class="text-center">
  <%= link_to "sort by popularity (default)", "/episodes?sort=popular&&keyword=#{@keyword_id}"%> | <%= link_to "sort by alphabetical order", "/episodes?sort=alphabetical&&keyword=#{@keyword_id}"%>
</p>


  <ul class="list-group list-group-flush">
    <% @episodes.each do |e|%>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to e.title, e %>
        <span class="badge badge-primary badge-pill"><%= e.favouriters.count %></span>
      </li>
    <% end %>
  </ul>
</section>

app/views/episodes/show.html.erb
<header>
  <h1 class="text-center display-4"><%= @episode.title%></h1>

<p class="text-center">
  An episode from: <%= link_to @podcast.name, @podcast%>
</p>

  <div class="text-center">
      <%= (button_to((@user.favourite_episodes.include?(@episode) ? "unfavourite" : "favourite"), favouritisation_path)) if @user %>
  </div>
</header>

<section class="w-75 mx-auto">

<p class="lead">
  <b>Show Notes: </b><%= @episode.description %>
</p>
<p class="text-left">
  Episode Keywords: <% @keywords.each do |k|%><%=link_to k.word, k %> | <% end %>
</p>
<p>&nbsp;</p>


<a name="favourite"></a>
<h4>Favourited by:</h4>
<%if @favouriters.count == 0 %>
  No one favourited this episode yet!
<%else%>
  <% @favouriters.each_slice(3) do |group| %>
  <div class="row">
    <% group.each do |f|%>
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <p class="card-text"><%= link_to f.username, f %></p>
        </div>
      </div>
     </div>
     <%end%>
  <p>&nbsp;</p>
  </div>
  <% end %>
<% end %>
<p>&nbsp;</p>

<a name="annotations"></a>
<h4>Annotations:</h4>
<% if @notes.count == 0 %>
  No notes available for this episode
<% else %>
  <% @notes.each_slice(3) do |group| %>
  <div class="row">
    <% group.each do |n| %>
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <p class="card-text"><%= n.content %></p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Notated by: <%= link_to n.notator.username, n.notator %></small>
        </div>
      </div>
     </div>
     <% end %>
  <p>&nbsp;</p>
  </div>
  <% end %>
<% end %>

<p>&nbsp;</p>

<a name="related_episodes"></a>
<h4>Other episodes from the same podcast:</h4>
<%if @siblings%>
  <% @siblings.each_slice(3) do |group| %>
  <div class="row">
    <% group.each do |s|%>
    <div class="col-md-4">
      <div class="card">
        <div class="card-body"><%= link_to s.title, s %>
          <p class="card-text"><%= s.description.first(100) %></p>
        </div>
        <div class="card-footer">
          <small class="text-muted"> </small>
        </div>
      </div>
     </div>
     <% end %>
  <p>&nbsp;</p>
  </div>
  <% end %>
<% end %>

<p>&nbsp;</p>
</section>