config/routes.rb
Rails.application.routes.draw do
  root to: "podcasts#index"

  #search routes
  get "/search", to: "searches#apple", as: "search"
  post "/search", to: "searches#results"

  # session routes
  get "/login_form", to: "sessions#login_form", as: "login_form"
  post "/login", to: "sessions#login", as: "login"
  delete "/logout", to: "sessions#logout", as: "logout"
  get "/profile", to: "users#profile", as: "profile"
  get "/profile/followships", to: "users#followshipslist", as: "followshipslist"

  # podcasts routes
  resources :podcasts, only: [:show, :index]
  post "/podcasts/:id/subscription", to: "podcasts#subscription", as: "subscription"
  get "/podcasts_query", to: "podcasts#query"

  #episode routes
  resources :episodes, only: [:show]
  post "/episodes/:id/favouritisation", to: "episodes#favouritisation", as: "favouritisation"
  post "/episodes/:id/play", to: "episodes#play", as: "play"

  # user routes
  resources :users
  post "/users/:id/followship", to: "users#followship", as: "followship"

  #keyword routes
  resources :keywords, only: [:show]

  # note routes
  resources :notes

end

app/models/keyword.rb
class Keyword < ApplicationRecord
  has_many :keywordisations
  has_many :episodes, through: :keywordisations

  def keyword_episodes_count
    "#{self.word} (#{self.episodes.count})"
  end

end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController

  def index
    if params[:sort]
      @keywords = Keyword.order(:word)
    else
      @keywords = Keyword.all.sort_by{|k| k.episodes.count}.uniq.reverse
    end
  end

  def show
    @keyword = Keyword.find(params[:id])
    @episodes = @keyword.episodes
  end

  def create
    byebug
    @keyword = Keyword.find_by(word: params[:word])
    redirect_to @keyword
  end

  private

end

app/views/keywords/index.html.erb
<div>
    <p class="text-center display-2">keywords</p>
</div>

<section class="w-75 mx-auto">
  <%=form_tag episodes_path, method: :get do%>
  <%end%>

<p class="text-center">
  <%= link_to "sort by number of episodes (default)", "/keywords"%> | <%= link_to "sort by alphabetical order", "/keywords?sort=alphabetical"%>
</p>

<p class="text-center">
<%= form_tag keywords_path do%>
     <%= text_field_tag :word, "", list: "keywords_autocomplete" %>
         <datalist id="keywords_autocomplete">
             <% Keyword.order(:name).each do |keyword| %>
                 <option value="<%= keyword.word %>">
             <% end %>
         </datalist>
 <%= submit_tag "Go" %>
 <-- <i>Would anyone help to move this to the middle?</i>
<% end %>
</p>

  <ul class="list-group list-group-flush">
    <% @keywords.each do |k|%>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to k.word, k %>
        <span class="badge badge-primary badge-pill"><%= k.episodes.count %></span>
      </li>
    <% end %>
  </ul>
</section>

app/views/keywords/show.html.erb
<header>
  <h1 class="text-center display-4"><%= @keyword.word%></h1>
</header>

<section class="w-75 mx-auto">

<a name="episodes"></a>
<h4>Episodes with this keyword:</h4>
<%if @episodes.count == 0%>
  No episodes are tagged with this keyword.
<%else%>
  <%@episodes.each_slice(3) do |group|%>
  <div class="row">
    <% group.each do |e|%>
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <p class="card-title"><%= link_to e.title, e%></p>
          <p class="card-text"><%= (e.description.length>100) ? e.description.first(80) + "..." : e.description%></p>
        </div>
        <div class="card-footer">
          <small class="text-muted">From <%=link_to e.podcast.name, e.podcast%></small>
        </div>
      </div>
     </div>
     <%end%>
  <p>&nbsp;</p>
  </div>
  <%end%>
<%end%>
</section>