config/routes.rb
Rails.application.routes.draw do
  root to: "podcasts#index"

  #search routes
  get "/search", to: "searches#apple", as: "search"
  post "/search", to: "searches#results"

  # session routes
  get "/login_form", to: "sessions#login_form", as: "login_form"
  post "/login", to: "sessions#login", as: "login"
  delete "/logout", to: "sessions#logout", as: "logout"
  get "/profile", to: "users#profile", as: "profile"
  get "/profile/followships", to: "users#followshipslist", as: "followshipslist"

  # podcasts routes
  resources :podcasts, only: [:show, :index]
  post "/podcasts/:id/subscription", to: "podcasts#subscription", as: "subscription"
  get "/podcasts_query", to: "podcasts#query"

  #episode routes
  resources :episodes, only: [:show]
  post "/episodes/:id/favouritisation", to: "episodes#favouritisation", as: "favouritisation"
  post "/episodes/:id/play", to: "episodes#play", as: "play"

  # user routes
  resources :users
  post "/users/:id/followship", to: "users#followship", as: "followship"

  #keyword routes
  resources :keywords, only: [:show]

  # note routes
  resources :notes

end

app/models/podcast.rb
class Podcast < ApplicationRecord
  has_many :episodes
  has_many :categorisations
  has_many :categories, through: :categorisations
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions

end

app/controllers/podcasts_controller.rb
require 'unirest'

class PodcastsController < ApplicationController
  def index
    if index_popularity_category_default || index_popularity_category
      @podcasts = Category.find(params[:category]).podcasts.uniq.sort_by { |p| p.subscribers.size }.reverse
      @categories = Category.order(:name)
      @category = "in #{Category.find(params[:category]).name}"
      @cat_id = params[:category]
    elsif index_alphabetical_category
      @podcasts = Category.find(params[:category]).podcasts.order(:name)
      @categories = Category.order(:name)
      @category = "in #{Category.find(params[:category]).name}"
      @cat_id = params[:category]
    elsif index_alphabetical_all
      @podcasts = Podcast.order(:name)
      @categories = Category.order(:name)
      @category = nil
    elsif index_popularity_all_default || index_all_default
      @podcasts = Podcast.all.sort_by { |p| p.subscribers.size }.reverse
      @categories = Category.order(:name)
      @category = nil
    end
  end

  def query
    @p_response = Unirest.get "https://listen-api.listennotes.com/api/v2/curated_podcasts?page=1",
      headers:{
        "X-ListenAPI-Key" => "7ec60ebc8b274880a3ab6c9759b26cd6",
      }

    @p_id = @p_response.body.length
  end

  def show
    @podcast = Podcast.find(params[:id])
    @episodes = @podcast.episodes
    @categories = @podcast.categories
    @subscribers = @podcast.subscribers
    @user = current_user
  end

  def subscription
    podcast = Podcast.find(params[:id])
    current_user.toggle_subscription(podcast)
    redirect_to podcast
  end

  private
  def podcast_params
    params.require(:category).permit(:category)
  end

  def index_all_default
    params[:sort] == nil && params[:category] == nil
  end

  def index_popularity_all_default
    params[:sort] == "popular" && params[:category] == ""
  end

  def index_alphabetical_all
    params[:sort] == "alphabetical" && params[:category].to_s.length == 0
  end

  def index_popularity_category_default
    params[:sort] == nil && params[:category].to_s.length > 0
  end

  def index_popularity_category
    params[:sort] == "popular" && params[:category].to_s.length > 0
  end

  def index_alphabetical_category
    params[:sort] == "alphabetical" && params[:category].to_s.length > 0
  end
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/podcasts/index.html.erb
<div>
    <p class="text-center display-2">podcasts</p>
    <p class="text-center display-4"><%= @category %></p>
</div>

<section class="w-75 mx-auto">
  <%=form_tag podcasts_path, method: :get do%>
    <%=select_tag "category", options_from_collection_for_select(@categories, :id, :category_podcasts_count), class:"custom-select custom-select-lg mb-3", onchange: "this.form.submit();", include_blank: "-- Filter by Category (number of podcasts in this category)"%>
  <%end%>

<p class="text-center">
  <%= link_to "sort by popularity (default)", "/podcasts?sort=popular&&category=#{@cat_id}"%> | <%= link_to "sort by alphabetical order", "/podcasts?sort=alphabetical&&category=#{@cat_id}"%>
</p>


  <ul class="list-group list-group-flush">
    <% @podcasts.each do |p|%>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="text-center">
          <a href="<%=podcast_path(p)%>"><img class="center-block img-responsive" src=<%=p.url%> width="50" height="50"></a>
        </div>
        <%= link_to p.name, p %>
        <span class="badge badge-primary badge-pill"><%= p.subscriptions.count %></span>
      </li>
    <% end %>
  </ul>
</section>

app/views/podcasts/query.html.erb
<h1><%= @response%></h1>

PODCAST INFO
@response[:"curated_lists"] #array of hashes
@response[:"curated_lists"][0] #first curator
@response[:"curated_lists"][0]["podcasts"][0] #first curator's first podcast
@response[:"curated_lists"][0]["podcasts"][0][:"id"]
@response[:"curated_lists"][0]["podcasts"][0][:"listennotes_url"]
@response[:"curated_lists"][0]["podcasts"][0][:"image"]
@response[:"curated_lists"][0]["podcasts"][0][:"title"]
@response[:"curated_lists"][0]["podcasts"][0][:thumbnail"]

What info do I want to extract?

app/views/podcasts/show.html.erb
<header>

  <h1 class="text-center display-4"><%= @podcast.name %></h1>

  <div class="container">
  <div class="text-center">
    <%if @podcast.url%><img class="center-block img-responsive" src=<%=@podcast.url%> width="300" height="300"><%end%>
  </div>
</div>

<p class="text-center">
  <% @podcast.categories.each do |c|%> <%= link_to c.name, "/podcasts?category=#{c.id}" %> | <% end %>
</p>

  <div class="text-center">
      <%= (button_to((@user.podcasts.include?(@podcast) ? "unsubscribe" : "subscribe"), subscription_path)) if @user %>
  </div>
</header>

<section class="w-75 mx-auto">

  <p class="lead">
    <%= @podcast.description %>
  </p>

  <div class="card-columns">
    <% @episodes.each do |e| %>
      <div class="card">
        <form class="card-body" method="post" action="/episodes/<%= e.id %>/favouritisation">
            <% if @user && @user.favourite_episodes.include?(e) %>
              <input type="image" src="https://image.flaticon.com/icons/png/128/148/148836.png" alt="unfavorite" width="25px" height="25px" style="float: right">
            <% else %>
              <input type="image" src="https://image.flaticon.com/icons/svg/660/660467.svg" alt="favorite" width="25px" height="25px" style="float: right">
            <% end %>
          <h5 class="card-title"><%= link_to e.title.capitalize, e %></h5>
          <p class="card-text"><%= e.description.first(200) %>...</p>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        </form>
        <div class="card-footer">
          <small class="text-muted"><% e.keywords.each do |k| %> <%= link_to k.word, k %> <% end %></small>
        </div>
      </div>
    <% end %>
  </div>

  <div>
    <h4>subscribers</h4>
      <ul>
        <% @subscribers.each do |s| %>
          <li><%= link_to s.username, s %></li>
        <%end%>
      </ul>
  </div>
</section>